version: 2

project_name: ado

builds:
  - id: ado
    binary: ado
    main: ./cmd/ado
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/anowarislam/ado/internal/meta.Version={{.Version}}
      - -X github.com/anowarislam/ado/internal/meta.Commit={{.Commit}}
      - -X github.com/anowarislam/ado/internal/meta.BuildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: anowarislam
    name: ado
  draft: false
  prerelease: auto

# Docker images
dockers:
  # AMD64 image
  - id: ado-amd64
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/anowarislam/ado:{{ .Version }}-amd64"
      - "ghcr.io/anowarislam/ado:latest-amd64"
    extra_files:
      - LICENSE
      - README.md
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI tool"
      - "--label=org.opencontainers.image.url=https://github.com/anowarislam/ado"
      - "--label=org.opencontainers.image.source=https://github.com/anowarislam/ado"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  # ARM64 image
  - id: ado-arm64
    goos: linux
    goarch: arm64
    dockerfile: goreleaser.Dockerfile
    use: buildx
    image_templates:
      - "ghcr.io/anowarislam/ado:{{ .Version }}-arm64"
      - "ghcr.io/anowarislam/ado:latest-arm64"
    extra_files:
      - LICENSE
      - README.md
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI tool"
      - "--label=org.opencontainers.image.url=https://github.com/anowarislam/ado"
      - "--label=org.opencontainers.image.source=https://github.com/anowarislam/ado"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

# Multi-arch Docker manifests
docker_manifests:
  - name_template: "ghcr.io/anowarislam/ado:{{ .Version }}"
    image_templates:
      - "ghcr.io/anowarislam/ado:{{ .Version }}-amd64"
      - "ghcr.io/anowarislam/ado:{{ .Version }}-arm64"

  - name_template: "ghcr.io/anowarislam/ado:latest"
    image_templates:
      - "ghcr.io/anowarislam/ado:latest-amd64"
      - "ghcr.io/anowarislam/ado:latest-arm64"

# Homebrew Formula (in-repository tap)
# See: https://goreleaser.com/customization/homebrew/
brews:
  - # Repository configuration - same repo, no separate token needed
    repository:
      owner: anowarislam
      name: ado  # Same repository
      branch: main
      # Note: Uses default GITHUB_TOKEN from workflow (no separate token needed)

    # Formula directory in same repository
    folder: Formula

    # Formula metadata
    name: ado
    homepage: https://github.com/anowarislam/ado
    description: "Composable command-line binary to replace ad-hoc shell scripts"
    license: MIT

    # Post-installation message
    caveats: |
      Get started with ado by running:
        ado meta info

      Configuration: ~/.config/ado/config.yaml
      Documentation: https://github.com/anowarislam/ado

    # Git commit configuration
    commit_author:
      name: ado-releaser
      email: noreply@github.com

    commit_msg_template: "chore(brew): update formula to {{ .Tag }}"

    # Skip upload for snapshot builds (local testing only)
    skip_upload: auto

    # Test block (Homebrew requirement)
    test: |
      system "#{bin}/ado", "meta", "info"
      assert_match version.to_s, shell_output("#{bin}/ado meta info")

    # Installation from bottle (precompiled binary)
    install: |
      bin.install "ado"
